// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package com.nicoletfear.Robot2015.commands;

import com.nicoletfear.Robot2015.Subsystems;

import edu.wpi.first.wpilibj.command.Command;

public class  Backward extends Command 
{

    public Backward(double timeout)
    {    	
    	super(timeout);
        requires(Subsystems.driveTrain);
    }

    // Called just before this Command runs the first time
   protected void initialize() 
    { 
	   Subsystems.driveTrain.autonomousDrive(-0.3);
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute()
    {
    	Subsystems.driveTrain.autonomousDrive(-0.3);
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() 
    {
    	return isTimedOut();
    }

    // Called once after isFinished returns true
    protected void end() 
    {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() 
    {
    	end();
    }
}
